substitutions:
  media_player_entity: media_player.bar_sonos # <- change this

  master_glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
  master_glyphs_ext: "ÀÁÂÃÄÅÈÉÊËÌÍÎÏÒÓÔÕÖØÙÚÛÜàáâãäåèéêëìíîïòóôõöøùúûüÇçÑñÝýÿ“”‘’–—"

packages:
  waveshare:
    url: https://github.com/inytar/waveshare-esp32-s3-touch-lcd-7-esphome
    files: [ waveshare-esp32-s3-touch-lcd-7.yaml ]

esphome:
  name: bar-media-display
  friendly_name: bar-media-display

  on_boot:
    priority: -200
    then:
      - lvgl.label.update:
          id: status_label
          text: "Starting up..."
      - delay: 800ms
      - lambda: ESP_LOGI("boot", "Boot stabilization delay complete");
      - lvgl.label.update:
          id: status_label
          text: "WiFi Connecting..."

esp32:
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "" # <- change this

ota:
  - platform: esphome
    password: "" # <- change this

safe_mode:
  reboot_timeout: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Bar-Media-Display"
    password: "" # <- change this

captive_portal:

globals:
  - id: lvgl_ready
    type: bool
    initial_value: "false"

# -------------------------------------------------------------
# DISPLAY TOGGLE SWITCH
# -------------------------------------------------------------
switch:
  - platform: template
    id: auto_display_off
    name: "Auto Display Off"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

    turn_on_action:
      - script.execute: update_display_power
    turn_off_action:
      - script.execute: update_display_power

    on_turn_on:
      - script.execute: update_display_power
    on_turn_off:
      - script.execute: update_display_power

# -------------------------------------------------------------
# DISPLAY + STATUS SCRIPTS
# -------------------------------------------------------------
script:

  # -------- STATUS LABEL --------
  - id: update_status_label
    mode: restart
    then:
      - lambda: |-
          std::string src = id(media_source).state;
          std::string st  = id(media_state).state;

          if (src.empty() || st.empty()) return;

          for (auto &c : src) c = tolower(c);
          for (auto &c : st)  c = tolower(c);

          bool no_media_info = (src == "tv" || src == "line_in");

          if (no_media_info) {
            lv_obj_add_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);

            if (src == "tv")      lv_label_set_text(id(status_label), "TV");
            if (src == "line_in") lv_label_set_text(id(status_label), "Line-In");
            return;
          }

          if (st == "playing")        lv_label_set_text(id(status_label), "Playing");
          else if (st == "paused")    lv_label_set_text(id(status_label), "Paused");
          else if (st == "buffering") lv_label_set_text(id(status_label), "Buffering...");
          else if (st == "idle")      lv_label_set_text(id(status_label), "Not Playing");
          else if (st == "off")       lv_label_set_text(id(status_label), "Off");
          else                        lv_label_set_text(id(status_label), "Not Playing");


  # -------- DISPLAY POWER + METADATA --------
  - id: update_display_power
    mode: restart
    then:
      - lambda: |-
          std::string src = id(media_source).state;
          std::string st  = id(media_state).state;
          bool auto_off   = id(auto_display_off).state;

          if (src.empty() || st.empty()) return;

          for (auto &c : src) c = tolower(c);
          for (auto &c : st)  c = tolower(c);

          bool no_media_info = (src == "tv" || src == "line_in");
          bool playing       = (st == "playing" || st == "buffering");

          if (no_media_info) {
            lv_obj_add_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);

            if (auto_off)
              id(display_off).execute();
            else
              id(display_on).execute();

            return;
          }

          if (!auto_off) {
            id(display_on).execute();
            lv_obj_clear_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);
            return;
          }

          if (playing) {
            id(display_on).execute();
            lv_obj_clear_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);
          } else {
            id(display_off).execute();
            lv_obj_clear_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);
          }

  - id: display_off
    then:
      - light.turn_off: lcdbacklight

  - id: display_on
    then:
      - light.turn_on: lcdbacklight


# -------------------------------------------------------------
# FONTS
# -------------------------------------------------------------
font:
  - file: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    id: font_40
    size: 40
    glyphs: "${master_glyphs}${master_glyphs_ext}"

  - file: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    id: font_32
    size: 32
    glyphs: "${master_glyphs}${master_glyphs_ext}"

  - file: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    id: font_26
    size: 26
    glyphs: "${master_glyphs}${master_glyphs_ext}"

  - file: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    id: font_22
    size: 22
    glyphs: "${master_glyphs}${master_glyphs_ext}"

  - file: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    id: font_18
    size: 18
    glyphs: "${master_glyphs}${master_glyphs_ext}"

  - file: "fonts/fa-solid-900.ttf"
    id: fa_wifi_24
    size: 24
    glyphs: "\uF1EB"


# -------------------------------------------------------------
# WIFI CONNECTIVITY
# -------------------------------------------------------------
binary_sensor:
  - platform: template
    id: wifi_connected
    internal: true
    lambda: return !isnan(id(wifi_rssi).state);

    on_state:
      - lambda: |-
          bool ok = id(wifi_connected).state;
          lv_obj_set_style_text_color(
            id(wifi_icon),
            lv_color_hex(ok ? 0x4AA382 : 0x8A2E2E),
            LV_PART_MAIN
          );

      - if:
          condition:
            lambda: 'return id(lvgl_ready);'
          then:
            - script.execute: update_status_label

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    update_interval: 60s
    disabled_by_default: true

# -------------------------------------------------------------
# TIME (CLOCK)
# -------------------------------------------------------------
time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: 0
        then:
          - lvgl.label.update:
              id: clock_label
              text: !lambda |-
                auto t = id(ha_time).now();
                int hr = t.hour % 12;
                if (hr == 0) hr = 12;
                char buf[32];
                sprintf(buf, "%d:%02d %s",
                        hr, t.minute,
                        t.hour >= 12 ? "PM" : "AM");
                return std::string(buf);

# -------------------------------------------------------------
# ARTWORK LOADER WITH SPINNER
# -------------------------------------------------------------
http_request:

online_image:
  - id: media_artwork
    url: "http://homeassistant.local:8123/local/placeholder.jpg"
    type: RGB565
    format: jpg
    resize: 280x280

    on_error:
      - lambda: |-
          ESP_LOGE("art", "Artwork request FAILED (HTTP error). Using placeholder.");
          lv_obj_add_flag(id(artwork_spinner), LV_OBJ_FLAG_HIDDEN);
          id(media_artwork).set_url("http://homeassistant.local:8123/local/placeholder.jpg");

    on_download_finished:
      - lambda: |-
          // Hide spinner when done
          lv_obj_add_flag(id(artwork_spinner), LV_OBJ_FLAG_HIDDEN);

          // Only show artwork in normal mode
          std::string src = id(media_source).state;
          for (auto &c : src) c = tolower(c);
          bool no_media_info = (src == "tv" || src == "line_in");
          if (no_media_info) return;

          lv_obj_clear_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
          lv_obj_clear_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
          lv_obj_clear_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);

      - lvgl.image.update:
          id: artwork_img
          src: media_artwork

      - lvgl.image.update:
          id: artwork_bg
          src: media_artwork

# -------------------------------------------------------------
# TEXT SENSORS — METADATA
# -------------------------------------------------------------
text_sensor:

  - platform: homeassistant
    id: media_friendly
    entity_id: ${media_player_entity}
    attribute: friendly_name
    on_value:
      - if:
          condition:
            lambda: 'return x.empty();'
          then:
            - lvgl.widget.hide: friendly_label
          else:
            - lvgl.label.update:
                id: friendly_label
                text: !lambda "return x;"
            - lvgl.widget.show: friendly_label

  - platform: homeassistant
    id: media_title
    entity_id: ${media_player_entity}
    attribute: media_title
    on_value:
      - if:
          condition:
            lambda: 'return x.empty();'
          then:
            - lvgl.widget.hide: title_label
          else:
            - lvgl.label.update:
                id: title_label
                text: !lambda "return x;"
            - lvgl.widget.show: title_label

  - platform: homeassistant
    id: media_artist
    entity_id: ${media_player_entity}
    attribute: media_artist
    on_value:
      - if:
          condition:
            lambda: 'return x.empty();'
          then:
            - lvgl.widget.hide: artist_label
          else:
            - lvgl.label.update:
                id: artist_label
                text: !lambda "return x;"
            - lvgl.widget.show: artist_label

  - platform: homeassistant
    id: media_album
    entity_id: ${media_player_entity}
    attribute: media_album_name
    on_value:
      - if:
          condition:
            lambda: 'return x.empty();'
          then:
            - lvgl.widget.hide: album_label
          else:
            - lvgl.label.update:
                id: album_label
                text: !lambda "return x;"
            - lvgl.widget.show: album_label

  - platform: homeassistant
    id: media_artwork_path
    entity_id: ${media_player_entity}
    attribute: entity_picture

    on_value:
      - online_image.set_url:
          id: media_artwork
          url: !lambda |-
            std::string path = x;

            if (path.empty()) return "IGNORE";

            if (path.size() > 4) {
              std::string ext = path.substr(path.size() - 4);
              for (auto &c : ext) c = tolower(c);
              if (ext == ".png") return "IGNORE";
            }

            if (path.length() > 300) return "IGNORE";

            if (path.rfind("http://", 0) == 0 ||
                path.rfind("https://", 0) == 0)
              return path;

            if (path.rfind("/api/media_player_proxy/", 0) == 0)
              return "http://homeassistant.local:8123/image_proxy" + path.substr(22);

            return "http://homeassistant.local:8123" + path;

      - lambda: |-
          // Begin loading, show spinner
          lv_obj_clear_flag(id(artwork_spinner), LV_OBJ_FLAG_HIDDEN);

          if (x == "IGNORE") {
            lv_obj_add_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
          }

# -----------------------------------------------------------
# MEDIA STATE SENSOR
# -----------------------------------------------------------
  - platform: homeassistant
    id: media_state
    entity_id: ${media_player_entity}
    on_value:
      - script.execute: update_status_label
      - script.execute: update_display_power

# -----------------------------------------------------------
# MEDIA SOURCE SENSOR
# -----------------------------------------------------------
  - platform: homeassistant
    id: media_source
    entity_id: ${media_player_entity}
    attribute: source
    on_value:
      - script.execute: update_status_label
      - script.execute: update_display_power


# -------------------------------------------------------------
# LVGL UI — WITH ARTWORK SPINNER
# -------------------------------------------------------------
lvgl:
  bg_color: 0x000000
  bg_opa: COVER

  on_ready:
    - lambda: |-
        id(lvgl_ready) = true;
        ESP_LOGI("lvgl", "LVGL ready");
        lv_obj_add_flag(id(artwork_img), LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(id(artwork_bg), LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(id(metadata_container), LV_OBJ_FLAG_HIDDEN);
    - lvgl.widget.hide: friendly_label
    - lvgl.widget.hide: title_label
    - lvgl.widget.hide: artist_label
    - lvgl.widget.hide: album_label

  widgets:

    # Toolbar
    - obj:
        id: toolbar
        width: 800
        height: 50
        align: TOP_MID
        bg_opa: TRANSP
        border_width: 0
        shadow_width: 0
        outline_width: 0
        pad_left: 12
        pad_right: 12
        pad_top: 6
        pad_bottom: 6

        widgets:
          - label:
              id: friendly_label
              hidden: true
              text: ""
              align: LEFT_MID
              text_font: font_22
              text_color: 0xD4A450

          - label:
              id: status_label
              text: "Starting..."
              align: CENTER
              text_font: font_18
              text_color: 0x777777

          - label:
              id: wifi_icon
              text: "\uF1EB"
              align: RIGHT_MID
              text_font: fa_wifi_24
              text_color: 0x8A2E2E

    # Background artwork
    - image:
        id: artwork_bg
        hidden: true
        src: media_artwork
        align: CENTER
        width: 800
        height: 480
        zoom: 6.0
        opa: 15%
        bg_opa: TRANSP

    # Foreground artwork
    - image:
        id: artwork_img
        hidden: true
        src: media_artwork
        align: LEFT_MID
        x: 40
        y: 0
        width: 260
        height: 260
        radius: 10
        border_color: 0xD4A450
        border_width: 4
        pad_all: 4
        bg_color: 0x012A20
        bg_opa: COVER

    # Artwork loading spinner
    - spinner:
        id: artwork_spinner
        hidden: true
        # align to the same parent as artwork_img
        align: LEFT_MID
        x: 138
        y: 0
        width: 60
        height: 60
        spin_time: 2s
        arc_length: 40deg  
        bg_opa: TRANSP
        arc_opa: 50%
        arc_color: 0x8A2E2E

    # Metadata block
    - obj:
        id: metadata_container
        hidden: true
        align: LEFT_MID
        x: 320
        y: 0
        width: 460
        height: 220
        bg_opa: TRANSP
        border_width: 0
        shadow_width: 0
        outline_width: 0
        pad_all: 0
        scrollable: false

        widgets:
          - label:
              id: title_label
              hidden: true
              align: TOP_RIGHT
              width: 460
              long_mode: SCROLL_CIRCULAR
              text: ""
              text_font: font_40
              text_color: 0xEEDFC7

          - label:
              id: artist_label
              hidden: true
              align: RIGHT_MID
              y: -20
              width: 460
              long_mode: SCROLL_CIRCULAR
              text: ""
              text_font: font_32
              text_color: 0xD4A450

          - label:
              id: album_label
              hidden: true
              align: RIGHT_MID
              y: 60
              width: 460
              long_mode: SCROLL_CIRCULAR
              text: ""
              text_font: font_26
              text_color: 0xB8B8B8

    # Clock
    - label:
        id: clock_label
        align: BOTTOM_RIGHT
        x: -25
        y: -25
        text: "--:--"
        text_font: font_40
        text_color: 0xD4A450
